### ISSUE TITLE
3 Protoype Routines

### ISSUE THREAD

**Issue by Augustine-** [RankOneSolutions/UpLift#3]
Pure Cardio
Pure Resistance
Pure Flexibility

Each will have 3 Exercises, list these attributes: 
- Muscle Group(s)
- Estimated time per rep
- Equipment required

**Comment by Mirix5** [comment]
**1 Strength**
https://old.reddit.com/r/Fitness/wiki/phraks-gslp

Day 1
- 3x5+ Chinups OR Barbell Rows (alternating)
- 3x5+ Overhead Press OR Bench Press (alternating)
- 3x5+ Squats
Day 2
- 3x5+ Chinups OR Barbell Rows (alternating)
- 3x5+ Overhead Press OR Bench Press (alternating)
- 1x5+ Deadlifts
Day 3
- 3x5+ Chinups OR Barbell Rows (alternating)
- 3x5+ Overhead Press OR Bench Press (alternating)
- 3x5+ Squats

**2 Cardio**
Choose a conditioning exercise. Go hard for 15 to 30 seconds, roughly.
Catch your breath. Don't "rest", just wait for the black spots to fade from your vision.
Repeat.
Stop after 10 to 20 minutes.

Battle Ropes: This is like sprinting for your upper body. Use a variety of undulation techniques. If you can go much over 30 seconds every round, then you're either a world class athlete, you're using dental floss, or you're phoning it in. Go hard. Make noise. Leave some blood on the ropes.
Sprints: Flats, hills, glaciers, with Jim Wendler on your back, etc.
Heavy Bag Work: Beat it like it's wearing an Affliction T-shirt.
Loaded Carries.
Fast Jump Rope: Double-unders if you have the coordination.
Medicine Ball Work: One of the best exercises here is to take a 100 to 150 pound med ball or Atlas stone, pick it up and toss it over one shoulder. Then turn around and repeat. Sadly, 100+ pound med balls are hard to find in most gyms, but they're out there.
Prowler or Sled Work: Push it, drag it, or throw it.

**3 Flexibility**
1. Foam Roll IT Band: 10-15 passes 
2. Foam Roll Adductors: 10-15 passes 
3. SMR Glutes (lax ball): 30sec. – 2min. 
4. Bent-knee Iron Cross x 5-10 each side
5. Roll-overs into V-sits x 10
6. Rocking Frog Stretch x 10
7. Fire Hydrant Circles x 10 fwd/10 bwd
8. Mountain Climbers x 10 each leg
9. Cossack Squats x 5-10 each side
10. Seated Piriformis Stretch x 20-30sec. each side
11. Rear-foot-elevated Hip Flexor Stretch x 5-10 reps (3sec. hold) each side
